### ISSUE TITLE
expose sync feature in mobile, wasm

### ISSUE THREAD

**Issue by boddumanohar** [0chain/gosdk#1178]
currently sync feature is not exposed in wasm or mobile.

**Comment by sunilmhta** [comment]
As per the discussions in the thread: https://0chain.slack.com/archives/C026YA5EYH3/p1693070221129689, 
For WASM, we want a functionality where we let the user select a folder from their local file system and then upload all the files from there. This should not require a new API to be exposed in wasm gosdk and should be doable with the existing multi upload functionality we have.

I tested it with the demo by following these steps:
1.     Added an input tag to let the user upload a folder instead of files:`<input id="inputSelectedDirectory" type="file" directory="" webkitdirectory="" /> <button id="btnUploadDirectory">UploadDirectory</button>`
2. In the btn click event, added the same code which is present for the files upload and it worked.


![Image](https://github.com/0chain/gosdk/assets/15699710/eb49d85a-7579-416b-a00a-7f36aa8532f7)



Will check for the mobile now and update the thread.

**Comment by sunilmhta** [comment]
Hi @boddumanohar , I checked the mobilesdk code and I can see that there already exist this API:
`func (a *Allocation) GetDiff(lastSyncCachePath string, localRootPath string, localFileFilters string, remoteExcludePaths string) (string, error)` which is used for the sync. What is the remaining work item here?

**Comment by sunilmhta** [comment]
marking as closed.
