### ISSUE TITLE
gosdk is wrongly tagged

### ISSUE THREAD

**Issue by hm90121** [0chain/gosdk#35]
Hi there,
       I am using gosdk with zboxcli and I think it is wrongly tagged
        v1.2.4 is in the master branch already, but not in tag which is why whenever I  am running  zbox version command  it displays 1.2.0 but actually it is 1.2.4 .

**Comment by satchinjoshi** [comment]
@hm90121 you are using `v1.2.4` 
If you check https://github.com/0chain/gosdk/blob/v1.2.4/core/version/version.go the version info is wrong there
 @guruhubb

**Comment by bbist** [comment]
This issue is resolved by PR https://github.com/0chain/gosdk/pull/42, which has been merged to master. Redundant previous tag v1.2.2 was removed, and previous tag v1.2.4 has been moved to v1.2.2. Current master is set at v1.2.2.
From now on, every intended release should first run `make getrev`, and increment fix the version manually in `gosdk/core/version/version.go`. This process could be automated to add auto-increment, but that's for later.
