### ISSUE TITLE
is it a security issue to save private key in js/wasm runtime?

### ISSUE THREAD

**Issue by cnlangzi** [0chain/gosdk#720]
is there any solution to get web-apps worked without keep wallet object(raw private key) in js/wasm runtime?

**Comment by cnlangzi** [comment]
@peterlimg  @dabasov  @guruhubb @ranajahanzaib @samtholiya

**Comment by sculptex** [comment]
@cnlangzi I am not sure, Talles also expressed this concern.

* First, What does metamask/myetherwallet do?
* Secondly, would splitting between different types of storage add security? E.g. is it feasible to decode on the fly from say browser storage combined with decrypt/mask/password in cookie storage?

**Comment by dabasov** [comment]
Yes, it is generally considered a security issue to save private keys in a JS/WASM runtime, especially if the private key is used for cryptographic operations. The reason for this is that JavaScript and WebAssembly are both client-side technologies, which means that the code is executed in the user's browser and can be accessed by anyone who has access to the browser or the device running the browser.

 few examples of how attacks on a browser could be executed to steal private keys saved in a JS/WASM runtime:

Malware or phishing attacks: Malware can infect a user's device and gain access to sensitive information, including private keys stored in the browser. Similarly, phishing attacks can trick users into entering their private key into a fake website, which can then be used to steal the key.

Browser vulnerabilities: Browsers are complex pieces of software, and vulnerabilities in the code can be exploited to gain unauthorized access to sensitive information. For example, a cross-site scripting (XSS) attack could allow an attacker to inject malicious code into a web page and steal private keys.

Rogue browser extensions: Browser extensions are pieces of software that run inside the browser and can have access to the same data as the browser itself. Malicious browser extensions can be used to steal private keys or other sensitive information.

Network eavesdropping: If a user is accessing a website over an unsecured network, an attacker could intercept and read the traffic, including any private keys being transmitted.

Physical access to the device: If an attacker gains physical access to a device running a browser, they could potentially extract private keys from the browser's storage.

**Comment by YarikRevich** [comment]
WASM can be easily disassembled. Even if we'd use some external storage service anyone can extract that data with the help of code injection.

**Comment by DamiFur** [comment]
I think it's definitively not a good idea to store a persistent private key associated with a user's wallet on the client side because of the motives exposed by @dabasov. In any case, if storing this information is unavoidable, at least it should be done within a session with a finite time limit. I'm far from being an expert on security, but a simple way to achieve this that comes to my mind is to use a changing hash that is updated every X minutes, then when the client requests the wallet's data, she receives the XORed version of the true private key with this changing hash. Whenever the user wants to use its private key on any operation on the server, her own version of the private key will be XORed again to recover her true private key. If anyone steals this information from the client, this information will expire after at most X minutes. If the wallet is registered in a distributed manner (for examples, on different miners/sharders/whatever) it is possible to use a seeded randomized function, so the hash used to mask the private keys are updated on the same way.

This is not infallible, of course, but it reduces the risk to a specific time window. There will always be security issues that will be unpreventable (e.g. a user looses her laptop seconds after logging in).

For what I see on the PR mentioned here, @cnlangzi added support for updating nounce wallet info, but for what I can see, it only updates balance information, so for what I understand, the client running wasm holds the actual private key associated with a wallet, is that correct?

I've been reviewing the wasmsdk code and I still have many doubts about how it works. For example, I haven't been able to understand where does the login information come from if you already have a wallet. I would very much appreciate it if someone could point me out into how wasm handles that.

**Comment by DamiFur** [comment]
[Here](https://github.com/0chain/gosdk/pull/1019/) is a proposal for a fix.

I'm basically removing the private key from javascript runtime and modifying the sign function to receive not only the hash that it has to sign but also the private key as a parameter. The private key is then recovered from the zbox client inside wasm. Since the client is a private variable in a go module, it should be inaccessible for the browser or any malicious code with access to the browsers console
