### ISSUE TITLE
improve `resty` package

### ISSUE THREAD

**Issue by cnlangzi** [0chain/gosdk#737]
as per @peterlimg mentioned on https://github.com/0chain/gosdk/pull/718#discussion_r1089708101

> We'd better use the ctx instead of coming up with a new timeout, the API caller should be able to control the timeout with the ctx param. Anyway, that will require the refactoring of the. resty package to drop the timeout param or make it optional, which could be done in another thread.

**Comment by aniketsingh03** [comment]
Was reading through `http/client.go`, and looks like there are 3 ways to cancel the req:
```go
// setRequestCancel sets req.Cancel and adds a deadline context to req
// if deadline is non-zero. The RoundTripper's type is used to
// determine whether the legacy CancelRequest behavior should be used.
//
// As background, there are three ways to cancel a request:
// First was Transport.CancelRequest. (deprecated)
// Second was Request.Cancel.
// Third was Request.Context.
// This function populates the second and third, and uses the first if it really needs to.
func setRequestCancel(req *Request, rt RoundTripper, deadline time.Time)
```

And the deadline that we pass to our resty obj (`resty.WithTimeout(resty.DefaultRequestTimeout)`), honors the incoming timeout from the request's context in addition to setting this deadline. So, if deadline > request's ctx timeout, then ctx is followed, whereas when deadline < request's ctx, then deadline is set as timeout.

```go
	var cancelCtx func()
	if oldCtx := req.Context(); timeBeforeContextDeadline(deadline, oldCtx) {
		req.ctx, cancelCtx = context.WithDeadline(oldCtx, deadline)
	}
```
So, if we want to restrict the caller to be able to set a longer deadline than the incoming request's ctx, then we can remove the timeout param, otherwise it won't make much difference imo.

Let me know your thoughts on this @cnlangzi @peterlimg

**Comment by aniketsingh03** [comment]
cc: @dabasov ^
