### ISSUE TITLE
flakiness in bl-update

### ISSUE THREAD

**Issue by boddumanohar** [0chain/gosdk#752]
There is some flakiness in bl-update, sometimes sharder returns `missing blobber` and other times it works. Not sure what's causing this. Another flakiness with bl-update is the rounding issue which is still frequent

![image](https://user-images.githubusercontent.com/9148277/216847256-1cbb37e9-8699-4b91-b340-c56385a1de32.png)
![image (1)](https://user-images.githubusercontent.com/9148277/216847261-7f3eb36d-3139-40b6-b04b-fa9cca4ffea6.png)

**Comment by aniketsingh03** [comment]
The mismatch is happening because of int64 conversion of float64 multiplication. This happens at compile time  and will always have some (non-deterministic) precision error. The following code:
```go
		if flags.Changed("read_price") {
			var rp float64
			if rp, err = flags.GetFloat64("read_price"); err != nil {
				log.Fatal(err)
			}
			blob.Terms.ReadPrice = common.ToBalance(rp)
		}
```
uses ToBalance which looks like:
```go
const tokenUnit = 1e10
type Balance int64

// ToBalance converts ZCN tokens to Balance.
func ToBalance(token float64) Balance {
	return Balance(token * tokenUnit)
}
```

So, the result for `ToBalance(2.01)` is `20099999999` and not `20100000000` because of float64 multiplication.

This error will show up whevever ToBalance is being called (ReadPrice, WritePrice, MinStake, MaxStake)

Possible solution:
One way to solve this is to add a 0.5 before converting to int, as in `return Balance(token * tokenUnit + 0.5)`

**Comment by dabasov** [comment]
we should return from API already rounded values, so need to fix all floats in responses in apis
