### ISSUE TITLE
[flake] `bl-update` returns `missing blobber` error

### ISSUE THREAD

**Issue by aniketsingh03** [0chain/gosdk#811]
Check the following screenshot - https://user-images.githubusercontent.com/9148277/216847256-1cbb37e9-8699-4b91-b340-c56385a1de32.png.

Latest occurence - https://github.com/0chain/system_test/actions/runs/4305246202/jobs/7507824703

This came up for the first time in #752

**Comment by mayank-2105** [comment]
Issue not reproducible easily on local as well as github tests due to flakiness. See sample run- [https://github.com/0chain/0chain/actions/runs/4712218420/jobs/8358637445](url)
Added a PR with the actual error logs to enable easy debugging as whenever the issue occcurs. #https://github.com/0chain/0chain/pull/2298
